### ISSUE TITLE
Completing Breakfast 

### ISSUE THREAD

**Issue by nyhdo93** [IntroToCode/CodeMates4_Fall23#1]
## 💬 Discussion topic

Completing Breakfast 

## ❗ Potential issues

1. Formatting for each sections
2. Completing the "Steps" for the recipe

## 👥 People to consult

@frankzhang95 @amarisskim1 @eliasmufa

## 📃 Details

Hey team! Could we review the breakfast recipe to ensure the formatting looks okay on your end? If formatting looks good, we'll just need to add in the "Steps". The recipe I used (https://cooking.nytimes.com/recipes/1012934-mushroom-omelet-with-chives) is linked.

**Comment by frankzhang95** [comment]
Sounds good, I will review the breakfast recipe.

**Comment by amarisskim1** [comment]
Sounds good, I'll look at breakfast now
